In [ ]:
#First, we call the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.graph_objects as go
import plotly.express as px

In [ ]:
data = pd.read_csv('/kaggle/input/consumers-in-the-restaurant/consumers.csv')
df = pd.DataFrame(data)
df

In [ ]:
df.describe(include ="all")

In [ ]:
#data cleaning

In [ ]:
df.info()

In [ ]:
df.isna().sum()

In [ ]:
df[df.Smoker.isna()]

In [ ]:
df[df.Transportation_Method.isna()]

In [ ]:
df[df.Marital_Status.isna()]

In [ ]:
df[df.Children.isna()]

In [ ]:
df[df.Occupation.isna()]

In [ ]:
df[df.Budget.isna()]

In [ ]:
df1= df.fillna(method='ffill', axis=1)
df1

In [ ]:
df1.isna().sum()

In [ ]:
df1.info()

In [ ]:
#Statistical description of data

In [ ]:
df1.describe(include ="all")

In [ ]:
df2 = df1.dropna()
df2

In [ ]:
#chart

In [ ]:
df2 = df1.groupby(pd.Grouper(key = "Budget")).count().reset_index()
df2 = df2.sort_values(by ='Occupation', ascending = False).iloc[:5]
fig, ax = plt.subplots()
ax.pie(df2["Occupation"], labels=df2["Budget"], autopct='%1.1f%%')
plt.tight_layout()

In [ ]:
location_counts = df2.groupby('City').size().reset_index(name='Count')
location_counts = location_counts.sort_values('Count', ascending=False)
plt.figure(figsize=(10,8), dpi=90)
sns.barplot(data=location_counts, x='City', y='Count')
plt.xticks(rotation=90)
plt.grid()

In [ ]:
fig = px.histogram(df2, x="Age",  template = 'plotly', title = 'Age - Count',
                     text_auto = True,  opacity=0.8)
fig.update_layout(bargap=0.3)
fig.show()

In [ ]:
plt.figure(figsize=(10,5))
sns.histplot(data=df2, x='Marital_Status' , color = 'teal')
plt.title('Count Of Marital_Status ( Histogram )', fontweight='bold', color = 'dimgray')
plt.show()

In [ ]:
sns.pairplot(data = data, hue= 'Occupation')
plt.show()